name: "App release"
on:
  push:
    tags:
      - '*'
jobs:
  trigger-app-release:
    uses: FLECS-Technologies/app-sdk/.github/workflows/trigger_app_release.yml@main
    with:
      app-name: tech.flecs.ample
      release-tag: ${{ github.ref }}
      app-version: ${{ github.ref_name }}
    secrets:
      APP_RELEASE_TOKEN: ${{ secrets.APP_RELEASE_TOKEN }}
